Fix/pham.nghia/conncet api cart
comartek/fs-clone-tinwin-retailer pull request #26
Opened 2022-10-13 08:20 UTC by nghiapt-comatek

**Description**

fix ui homescreen và giỏ hàng với api 

**Evidence (photos)**
![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 15 16 39](https://user-images.githubusercontent.com/111269414/195542466-955a6ca0-1375-48ed-8e90-ca646f727345.png)
![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 15 17 01](https://user-images.githubusercontent.com/111269414/195542477-fa591418-0981-41be-8002-8ff63e20c1cc.png)

![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 15 16 36](https://user-images.githubusercontent.com/111269414/195542433-df7dfc88-2c55-440d-b3f7-ad7b91787c55.png)

![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 15 16 24](https://user-images.githubusercontent.com/111269414/195542386-9b325f0e-0cf5-4b09-8129-2f62656bbfbc.png)
![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 15 16 30](https://user-images.githubusercontent.com/111269414/195542416-b0d14ac7-e5d3-4ce1-8fbc-8e3f42ff90e2.png)

2022-10-13 08:46 UTC, phuongna-comartek requested changes

2022-10-13 08:46 UTC, phuongna-comartek commented on src/Screens/tabBarScreen/HomeScreen.tsx
> +  });
đoạn này là định làm gì đây?
chỗ này vi phạm [rule of hooks](https://reactjs.org/docs/hooks-rules.html)

2022-10-13 08:46 UTC, phuongna-comartek commented on src/hooks/useToken.tsx
> +
chỗ logic này đang bị rerender lại rất nhiều

2022-10-13 08:46 UTC, phuongna-comartek commented on src/hooks/useToken.tsx
> +
Tìm hiểu lại về cơ chế hook & và render của react

2022-10-13 09:21 UTC, nghiapt-comatek commented
đã fix logic

2022-10-14 02:09 UTC, phuongna-comartek requested changes

2022-10-14 02:09 UTC, phuongna-comartek commented on src/hooks/useCustomTotalCart.ts
> +
đoạn này tương tự lỗi hôm qua

2022-10-14 02:25 UTC, nghiapt-comatek commented on src/hooks/useCustomTotalCart.ts
> +
đã fix lại usehooks

2022-10-14 02:32 UTC, phuongna-comartek approved these changes

2022-10-14 02:32 UTC, merged