Fix/pham.nghia/add product to cart
comartek/fs-clone-tinwin-retailer pull request #29
Opened 2022-10-18 02:25 UTC by nghiapt-comatek

**Description** 
conect api home screen 
thêm chức năng sắp xếp

2022-10-18 04:59 UTC, phuongna-comartek requested changes

2022-10-18 04:59 UTC, phuongna-comartek commented on src/Screens/cartScreen/reduxCart/CartSlide.ts
> +    const getToken = await AsyncStorage.getItem('token');
logic gắn token để vào interceptor, hỏi Quân để biết thêm chi tiết

2022-10-18 04:59 UTC, phuongna-comartek commented on src/components/flatlist/FlastListNewGoodsHome.tsx
> +                {item.ratingAvg !== null ? (
check lưu ý trong MS Team thread
```suggestion
                {!!item.ratingAvg ? (
```

2022-10-18 07:25 UTC, nghiapt-comatek commented on src/components/flatlist/FlastListNewGoodsHome.tsx
> +                {item.ratingAvg !== null ? (
fix done

2022-10-19 03:05 UTC, phuongna-comartek commented on src/hooks/useCustomSortDataHome.ts
> +        return (items = [...dataSearchHome]);
viết như này nghĩa là sao? gán giá trị cho `items` xong return `items`?

2022-10-19 03:20 UTC, phuongna-comartek approved these changes

2022-10-19 03:20 UTC, merged